// Generated by dts-bundle v0.4.3

declare module 'phoenix-tools' {
    export { json } from 'phoenix-tools/lib/json';
}

declare module 'phoenix-tools/lib/json' {
    export var json: {
        loadFromFile: (fileName: string) => Promise<any>;
    };
}

